version: 2
jobs:
  build:
    docker:
      - image: docker:dind
    working_directory: /snowGlobe
    steps:
      - run:
         name: Update APK
         command: apk update
      - run:
         name: Install Image Dependencies
         command: apk add git openssh-client ca-certificates openjdk8 bash py-pip
      - run:
         name: Install Docker Compose
         command: pip install docker-compose
      - checkout
      - run:
          name: Pull tags
          command: /bin/bash -c "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
      - run:
          name: Start Docker Daemon
          command: nohup dockerd --host=unix:///var/run/docker.sock  --host=tcp://0.0.0.0:2375 --storage-driver=vfs &
      - run:
          name: Test
          command: ./gradlew test
      - run:
          name: Build
          command: ./gradlew build
      - store_artifacts:
          path: build/reports/
          destination: reports


