version: 2
jobs:
  build:
    machine: true
    working_directory: ~/snowGlobe
    steps:
      - checkout
      - run:
          name: Pull tags
          command: /bin/bash -c "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"

      - run:
          name: Unit Tests
          command: ./gradlew test

      - run:
          name: Integration Tests
          command: ./gradlew integrationTest

      - run:
          name: Build
          command: |
             gpg --output certs/private.key --batch --yes --passphrase $PRIVATE_KEY_ENC_PASSWORD --decrypt certs/private.key.enc
             gpg --yes --batch --import certs/private.key
             gpg --import certs/public.key
             rm --force certs/private.key
             ./gradlew build

      - deploy:
          name: Publish Upstream Bounce Container
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              docker push krogersnowglobe/upstream-bounce-app:latest
            fi

      - store_artifacts:
          path: build/reports
          destination: reports
      - store_artifacts:
          path: build/libs
          destination: libs
      - store_artifacts:
          path: build/pom
          destination: pom


